### ISSUE TITLE
dany.armstrong90 - Auction.sol#createBid: Tokens may be sold a little cheaper by front-run attack.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-nounsbuilder-judging#176]
dany.armstrong90

medium

# Auction.sol#createBid: Tokens may be sold a little cheaper by front-run attack.

## Summary
When an attacker who is monitoring mempool detects the call to `Auction.sol#createBid` function, he will front-run it with a little lower price than the proposed price of the original bid.
So the attacker's bid will be accepted and the original one reverted.
The original bidder has to bid again at a price `minBidIncrement` percent higher than the attacker's price, and he considers that this price is not reasonable and exits the auction.
Thus, the token is auctioned slightly less than the price available.

## Vulnerability Detail
Example:
1. Suppose that only `bidder1` and `bidder2` pariticipate in the auction and `minBidIncrement = 10`.
2. `bidder2` first monitors mempool without bidding and when the calling `createBid` of `bidder1` is detected, he performs front-run attack at the cost of `msg.value = bidder1.msg.value * 0.95` . 
3. For instance, when `bidder1` calls `createBid` function with `msg.value == 1000`, `bidder2` calls `createBid` function before than `bidder1` with `msg.value == 950` and raised gas price.
4. So the `bidder2`'s bid is accepted and the original one of `bidder1` reverted.
5. `bidder1` considers that it is impractical to offer at a price `950 * 1.1 == 1045` and exits the auction.
5. After all, the token that could be sold at `1000` is sold at a price of `950`.

## Impact
Tokens may be sold a little cheaper by front-run attack.

## Code Snippet
https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/auction/Auction.sol#L214

## Tool used
Manual Review

## Recommendation
The purpose of using `minBidIncrement` is to prevent the auction deadline from extending by raising the offer value very small (e.g. 1) than the `lastHighstBid`.
In the case of `msg.timestamp == lastBidTime`, we do not need to apply `minBidIncrement`, since the auction deadline does not extend.
So insert the `lastBidTime` field to `Auction` struct and set `minBid = lastHighstBid + 1` in `_createBid` function when `msg.timestamp == lastBidTime`.

**Comment by web3-master** [comment]
Escalate

The token that could be sold at 1000 is sold at a price of 950 because of this issue.
This is not intended system behavior.
Because gas cost for front run is very tiny(it is a little bigger than usual bid operation), attackers are incentivized to use this vulnerability.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> The token that could be sold at 1000 is sold at a price of 950 because of this issue.
> This is not intended system behavior.
> Because gas cost for front run is very tiny(it is a little bigger than usual bid operation), attackers are incentivized to use this vulnerability.
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
@neokry you might want to take a look at this issue.

In my opinion, there is no fix to this, because the front-running possibilities could be endless between bidders.

**Comment by neokry** [comment]
I agree no fix here. also don’t really see this as a loss this is a part of the auction mechanism anyone can bid the minimum amount

**Comment by Czar102** [comment]
This is very much like frontrunning an AMM swap just so that someone else's swap would revert – you can't have control over this, and LPs may have a net loss of fees (they would have gotten more otherwise).

The model expects to sell the token up to 1/11 below the potential selling price due to the +10% rule, which prevents a griefing issue.

I think this is low/invalid.

**Comment by Czar102** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [web3-master](https://github.com/sherlock-audit/2023-09-nounsbuilder-judging/issues/176/#issuecomment-1857811758): rejected
