### ISSUE TITLE
0x70C9 - L2MigrationDeployer doesn't enforce its address to be the founder[0]

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-nounsbuilder-judging#186]
0x70C9

medium

# L2MigrationDeployer doesn't enforce its address to be the founder[0]

## Summary
The comment in [line 86 of the L2MigrationDeployer contract](https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/deployers/L2MigrationDeployer.sol#L86) says that "The address of this deployer must be set as founder 0". The documentation provided by the project also entails this:

> The caller must set the L2MigrationDeployer.sol contract as the first founder (with 0 allocation) so it can manage setup.

However, the `deploy` function doesn't enforce the `founder 0` to be the `L2MigrationDeployer` address, and failing to do so invalidates the usage of other contract functions such as `renounceOwnership`.

## Vulnerability Detail
The `deploy` function passes all inputs to `Manager.deploy` function without doing checks on such inputs:

```solidity
    function deploy(
        IManager.FounderParams[] calldata _founderParams,
        IManager.TokenParams calldata _tokenParams,
        IManager.AuctionParams calldata _auctionParams,
        IManager.GovParams calldata _govParams,
        MerkleReserveMinter.MerkleMinterSettings calldata _minterParams
    ) external returns (address token) {
        if (_getTokenFromSender() != address(0)) {
            revert DAO_ALREADY_DEPLOYED();
        }

        // Deploy the DAO
        (address _token, , , , ) = IManager(manager).deploy(_founderParams, _tokenParams, _auctionParams, _govParams);
```

Noteworthy, it doesn't check that `founder 0` is actually `address(this)`. This means that sensitive functions such as `renounceOwnership` will not be callable, since `L2MigrationDeployer` will not be the owner of `token` and `auction`.

## Impact
Function `renounceOwnership` will not be callable, since `L2MigrationDeployer` will not be the owner of `token` and `auction`.

## Tool used
Manual Review

## Recommendation
Add an additional check in the `deploy` function:

```solidity
require(_founderParams[0].wallet == address(this), "L2MigrationDeployer: Founder must be the deployer contract");
```

**Comment by 0x70C9** [comment]
@nevillehuang The known issue states that the address must be set as the first founder in the founders array or the call will revert. However, this is not the case. Indeed, as long as the address in the founders array is not zero, the deployment will not revert. 

```solidity
if ((founder = _founderParams[0].wallet) == address(0)) revert FOUNDER_REQUIRED();
```

Instead, the deployment will succeed. The impact is that, even though the deployment succeeds, some functions like `renounceOwnership` will not be callable.
