### ISSUE TITLE
Juntao - Minted tokens' attributes will be lost and can never be regenerated if new default metadata renderer is set

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-nounsbuilder-judging#200]
Juntao

high

# Minted tokens' attributes will be lost and can never be regenerated if new default metadata renderer is set

## Summary
Minted tokens' attributes will be lost and can never be regenerated if new default metadata renderer is set.

## Vulnerability Detail
Protocol provides [setMetadataRenderer(...)](https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/manager/Manager.sol#L169-L191) function for token owner to set new metadata renderer:
```solidity
metadata = address(new ERC1967Proxy(_newRendererImpl, ""));
daoAddressesByToken[_token].metadata = metadata;

if (_setupRenderer.length > 0) {
    IBaseMetadata(metadata).initialize(_setupRenderer, _token);
}

IToken(_token).setMetadataRenderer(IBaseMetadata(metadata));
```
When a new token is [minted](https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/token/Token.sol#L248-L259), `IBaseMetadata`'s [onMinted(...)](https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/token/metadata/interfaces/IBaseMetadata.sol#L32) function will be called to generate attributes for the token.
BuidlerDAO providers a default implementation of `IBaseMetadata` and its corresponding [onMinted(...)](https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/token/metadata/MetadataRenderer.sol#L242-L277) function, which can only be called by `Token` contract:
```solidity
function onMinted(uint256 _tokenId) external override returns (bool) {
    // Ensure the caller is the token contract
    if (msg.sender != settings.token) revert ONLY_TOKEN();

    // Compute some randomness for the token id
    uint256 seed = _generateSeed(_tokenId);

    // Get the pointer to store generated attributes
    uint16[16] storage tokenAttributes = attributes[_tokenId];

    // Cache the total number of properties available
    uint256 numProperties = properties.length;

    if (numProperties == 0) {
        return false;
    }

    // Store the total as reference in the first slot of the token's array of attributes
    tokenAttributes[0] = uint16(numProperties);

    unchecked {
        // For each property:
        for (uint256 i = 0; i < numProperties; ++i) {
            // Get the number of items to choose from
            uint256 numItems = properties[i].items.length;

           // Use the token's seed to select an item
            tokenAttributes[i + 1] = uint16(seed % numItems);

            // Adjust the randomness
            seed >>= 16;
        }
    }

    return true;
}
```
The problem is that if this default implementation is used to replace the current metadata render after some tokens have been minted, then the minted tokens will lose attributes, even worse, because the `onMinted(...)` function is called only when a new token is minted by `Token` contract, so there is no way to regenerated attributes for those minted tokens.

Please note, setting new metadata render when there are some tokens have been mintet is a __valid input__ for the trusted token owner, and even if there is no token minted, an eligible user may still mint tokens from `MerkleReserveMinter ` before new metadata render is set, due to the random ordering of transactions.

Please see blew test codes and run in `Token.t.sol` to verify:
```solidity
   function test_Audit() public {
        deployMock();

        vm.prank(token.auction());
        uint256 tokenId = token.mint();

        // tokenURI can be retrieved before setting new metadata render
        token.tokenURI(tokenId);

        vm.startPrank(token.owner());

        manager.setMetadataRenderer(address(token), manager.metadataImpl(), tokenParams.initStrings);

        string[] memory names = new string[](1);
        names[0] = "testing";
        MetadataRendererTypesV1.ItemParam[] memory items = new MetadataRendererTypesV1.ItemParam[](2);
        items[0] = MetadataRendererTypesV1.ItemParam({ propertyId: 0, name: "failure1", isNewProperty: true });
        items[1] = MetadataRendererTypesV1.ItemParam({ propertyId: 0, name: "failure2", isNewProperty: true });
        MetadataRendererTypesV1.IPFSGroup memory ipfsGroup = MetadataRendererTypesV1.IPFSGroup({ baseUri: "BASE_URI", extension: "EXTENSION" });
        MetadataRenderer(token.metadataRenderer()).addProperties(names, items, ipfsGroup);

        vm.stopPrank();

        // tokenURI can not be retrieved after setting new metadata render
        bytes4 selector = bytes4(keccak256("TOKEN_NOT_MINTED(uint256)"));
        vm.expectRevert(abi.encodeWithSelector(selector, tokenId));
        token.tokenURI(tokenId);
    }
```

## Impact
Token can not be properly rendered, because of a lack of attributes.

## Code Snippet
https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/token/Token.sol#L258

## Tool used
Manual Review

## Recommendation
Add a new function in `Token` contract for token owner to call `onMinted(...)` function to generate attributes for the minted tokens after new metadata render is set.

**Comment by juntzhan** [comment]
Escalate

This is a valid issue:
1. The root cause is in in-scope file and fix is in in-scope file, so the issue should apply to this contest;
2. Token attributes are lost permanently, Token hence cannot be rendered properly, it's permanent DOS;
3. It's almost certain that a Token (NFT) which cannot be rendered properly would be of low value in secondary market, user hence suffer a loss of funds due to price dumping.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This is a valid issue:
> 1. The root cause is in in-scope file and fix is in in-scope file, so the issue should apply to this contest;
> 2. Token attributes are lost permanently, Token hence cannot be rendered properly, it's permanent DOS;
> 3. It's almost certain that a Token (NFT) which cannot be rendered properly would be of low value in secondary market, user hence suffer a loss of funds due to price dumping.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
@juntzhan as a auditor, I agree with all your points but because of sherlock rules I think this likely will be invalid because the token is not actually lost and based on this comment [here](https://github.com/sherlock-audit/2023-09-nounsbuilder-judging/issues/144#issuecomment-1843504493) where sponsor noted there is no existing secondary markets for any DAOS currently deployed.

**Comment by vararg** [comment]
Will post it here to bring some context from discussion in discord, maybe it can be useful during issue evaluation.

Auditors wasn't informed about NFT ecosystem, and currently your main argument as I see is about ecosystem and the fact that is not affected.

But if we speak about ecosystem let's take step back and understand what exactly we are auditing, Nouns Builder It's a some kind of b2b(sorry for bad comparison) solution where as stated in the doc(https://docs.zora.co/docs/smart-contracts/nouns-builder/intro) primary user can deploy their DAOs and make auctions for secondary users. So we are auditing a Builder solution that from the architecture point of view can be added as component into different ecosystems and secondary markets also can be a part of such.
And our reports is more about abstractions of contracts(interfaces) and cross contract communication that will lead to secondary users loses(NFT metadata change is a major concern for whole NFT concept).

**Comment by nevillehuang** [comment]
While I can see the view of invalidating this issue, I agree with @juntzhan @vararg that this issue could be a valid medium severity issue, only IF the metadata renderer cannot be reinstated by the DAO and the original metadata cannot be recovered.

I agree with them in the sense that metadata is an essential part of the NFT and what constitutes most of the value towards an NFT, so if the above scenario i highlighted is possible, this could be a valid medium severity issue, given meta data change can be initiated from normal changes.

**Comment by neokry** [comment]
metadata can be recovered by changing back to the original renderer address

**Comment by vararg** [comment]
@neokry it can't in case if any token minted on new renderer, because in that case you will end up with two rendererers points to one dao state.

**Comment by neokry** [comment]
Like I mentioned we are shipping a fix for this with a new renderer that is not in scope for this contest. since this issue is in the metadata renderer I don’t think this should be considered.

**Comment by nevillehuang** [comment]
If the current out of scope `MetaDataRenderer.sol` directly affects the above mentioned situation, and the sponsor simply states they are working on a fix with a completely different contract, seems very unfair to watsons since it is fair for them to assume the current `MetadataRenderer.sol` is used and that there is no other renderers in place.

According to sherlock [rules](https://docs.sherlock.xyz/audits/judging/judging#iii.-some-standards-observed) here under 7. contract scope:

> 2. In case the vulnerability exists in a library and an in-scope contract uses it and is affected by this bug this is a valid issue.

Definitely in support of validating issue and leaning towards medium severity.

**Comment by Czar102** [comment]
It seems to me that it's the Metadata Renderer's fault if it's not backfilling metadata for tokens minted in the past. The example that was given is an out-of-scope contract.

Hence:
1. The root cause can be considered to be out of scope.
2. Token attributes can be backfilled, even with a new Metadata Renderer.
3. Secondary market pricing is out of scope, though core functionality breaking isn't.

I think this issue is invalid.

**Comment by Czar102** [comment]
@nevillehuang please note that `MetadataRenderer` is not a library, but a contract and it is not inherited by the codebase, so the rule you quoted does **not** apply here.

**Comment by nevillehuang** [comment]
@Czar102 agree with you decision, sorry for the confusion. Glad watsons still brought up this issue so that sponsors are aware.

**Comment by Czar102** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [juntzhan](https://github.com/sherlock-audit/2023-09-nounsbuilder-judging/issues/200/#issuecomment-1855166598): rejected
