### ISSUE TITLE
0xhacksmithh - Calculation of `minBid` is incorrect as per Code comments

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-nounsbuilder-judging#282]
0xhacksmithh

medium

# Calculation of `minBid` is incorrect as per Code comments

## Vulnerability Detail
In `_createBid()` Calculation of `minBid` occurs as follows
```solidity
                // Compute the minimum bid
                minBid = lastHighestBid + ((lastHighestBid * settings.minBidIncrement) / 100);
```
https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/auction/Auction.sol#L214

Where  `settings.minBidIncrement` is set with `INITIAL_MIN_BID_INCREMENT_PERCENT` in `initialize()`
```solidity
        settings.minBidIncrement = INITIAL_MIN_BID_INCREMENT_PERCENT;
```
https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/auction/Auction.sol#L131

Where as per code comment ` INITIAL_MIN_BID_INCREMENT_PERCENT` is in `bps` 
```solidity
    /// @notice Min bid increment BPS
    uint8 private immutable INITIAL_MIN_BID_INCREMENT_PERCENT = 10;
```
https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/auction/Auction.sol#L45-L46

So whole calculation for `minBid` is wrong as `settings.minBidIncrement` in `bps`. Instead of `100` divisor should be `10_000` or constant `BPS_PER_100_PERCENT`

## Impact
As per calculation of `minBid` 100 divisor used, so percentage of increment corresponding to `lastHighestBid` will be too high.

Let say  `lastHighestBid` is 1000ETH
 `settings.minBidIncrement` is 10
so percentage of Bid increment should = (1000 * 10) / 10000 = 1ETH
But currently it is = (1000 * 10) / 100 = 100ETH 
## Code Snippet
https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/auction/Auction.sol#L214
https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/auction/Auction.sol#L45-L46

## Tool used

Manual Review

## Recommendation
code should be
```diff
                // Compute the minimum bid
-               minBid = lastHighestBid + ((lastHighestBid * settings.minBidIncrement) / 100);

+               minBid = lastHighestBid + ((lastHighestBid * settings.minBidIncrement) / BPS_PER_100_PERCENT);
```

**Comment by 0xhacksmithh** [comment]
Escalate
Here code comment saying that `INITIAL_MIN_BID_INCREMENT_PERCENT` is in BPS. It set to 10 initialy. So it will equivalent to 0.01%. As code comment is source of truth while auditing and we previously notice many protocols use BPS for fee, percentage etc. Here according to code comment `New Bid` at least 0.01% greater than old, while in `Bid` calculation it shows 10% increament. I understand that protocol wants 10% increament and in current implementation it achieving it, but a/c code comments it should be 0.01%(10 bps). So I submitted this bug considering code comment(as its only source of truth available).

**Comment by sherlock-admin2** [comment]
> Escalate
> Here code comment saying that `INITIAL_MIN_BID_INCREMENT_PERCENT` is in BPS. It set to 10 initialy. So it will equivalent to 0.01%. As code comment is source of truth while auditing and we previously notice many protocols use BPS for fee, percentage etc. Here according to code comment `New Bid` at least 0.01% greater than old, while in `Bid` calculation it shows 10% increament. I understand that protocol wants 10% increament and in current implementation it achieving it, but a/c code comments it should be 0.01%(10 bps). So I submitted this bug considering code comment(as its only source of truth available).

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by 0xhacksmithh** [comment]
> Here code comment saying that `INITIAL_MIN_BID_INCREMENT_PERCENT` is in BPS. It set to 10 initialy. So it will equivalent to 0.01%. As code comment is source of truth while auditing and we previously notice many protocols use BPS for fee, percentage etc. Here according to code comment `New Bid` at least 0.01% greater than old, while in `Bid` calculation it shows 10% increament. I understand that protocol wants 10% increament and in current implementation it achieving it, but a/c code comments it should be 0.01%(10 bps). So I submitted this bug considering code comment(as its only source of truth available).

**Comment by nevillehuang** [comment]
@neokry Is this a typo? Even if it is intended to use BPS, instead of 1%, I don't see how this this could be medium severity given it:

1. Doesn't cause a loss of funds
2. Doesn't cause a permanent DoS of auction

**Comment by 0xhacksmithh** [comment]
> @neokry Is this a typo? Even if it is intended to use BPS, instead of 1%, I don't see how this this could be medium severity given it:
> 
> 1. Doesn't cause a loss of funds
> 2. Doesn't cause a permanent DoS of auction

I understand that there is no fund loss here, and as of my understanding in auctions there should some difference in subsequent bids otherwise bids become continuous like 100,101,102. Here **if go through code comment**, next bid will (oldBid + 10%oldBid) but it should (oldBid + 0.1oldBid) as considering BPS. So here problem is that newBid is will be high than it should be(10% instead of 0.1%) that should in example in report

**Comment by neokry** [comment]
the comment is inaccurate. prev devs did not change the comment at some point and it was left in @nevillehuang
