### ISSUE TITLE
chaduke - Token.updateFounders() might clear the wrong tokenRecipient[baseTokenId], as a result, not all old founders might be deleted.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-nounsbuilder-judging#72]
chaduke

medium

# Token.updateFounders() might clear the wrong tokenRecipient[baseTokenId], as a result, not all old founders might be deleted.

## Summary
Token.updateFounders() might clear the wrong tokenRecipient[baseTokenId], as a result, not all old founders might be deleted. 

## Vulnerability Detail
``Token.updateFounders()`` will allow the owner to delete the list of old founders and add a new set of founders. It uses reverse engineering to find which ``tokenRecipient[baseTokenId]`` to clear. The problem is that for each founder, it starts from ``baseTokenId = 0`` instead of from ``baseTokenId =  reservedUntilTokenId``.

[https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/token/Token.sol#L412](https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/token/Token.sol#L412)

This is not consistent with function  ``addFounders()``, which starts from ``baseTokenId =  reservedUntilTokenId`` for each founder to find   the available entry in ``tokenRecipient``:

[https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/token/Token.sol#L161](https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/token/Token.sol#L161)

As a result, the wrong ``tokenRecipient[baseTokenId]`` will be deleted by updateFounders() while some existing founders will not be deleted from ``tokenRecipient``. The final result might have more founders than desired. 

## Impact

The wrong ``tokenRecipient[baseTokenId]`` will be deleted by updateFounders() while some existing founders will not be deleted from ``tokenRecipient``. The final result might have more founders than desired. 

## Code Snippet
[https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/token/Token.sol#L375-L432](https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/token/Token.sol#L375-L432)

## Tool used
VSCode, Foundry

Manual Review

## Recommendation

 starts from ``baseTokenId =  reservedUntilTokenId`` to find the baseTokenId for each founder:

```diff
function updateFounders(IManager.FounderParams[] calldata newFounders) external onlyOwner {
        // Cache the number of founders
        uint256 numFounders = settings.numFounders;

        // Get a temporary array to hold all founders
        Founder[] memory cachedFounders = new Founder[](numFounders);

        // Cannot realistically overflow
        unchecked {
            // Add each founder to the array
            for (uint256 i; i < numFounders; ++i) {
                cachedFounders[i] = founder[i];
            }
        }

        // Keep a mapping of all the reserved token IDs we're set to clear.
        bool[] memory clearedTokenIds = new bool[](100);

        unchecked {
            // for each existing founder:
            for (uint256 i; i < cachedFounders.length; ++i) {
                // copy the founder into memory
                Founder memory cachedFounder = cachedFounders[i];

                // Delete the founder from the stored mapping
                delete founder[i];

                // Some DAOs were initialized with 0 percentage ownership.
                // This skips them to avoid a division by zero error.
                if (cachedFounder.ownershipPct == 0) {
                    continue;
                }

                // using the ownership percentage, get reserved token percentages
                uint256 schedule = 100 / cachedFounder.ownershipPct;

                // Used to reverse engineer the indices the founder has reserved tokens in.
-                uint256 baseTokenId;
+               uint256 baseTokenId = uint256 baseTokenId = reservedUntilTokenId;
                for (uint256 j; j < cachedFounder.ownershipPct; ++j) {
                    // Get the next index that hasn't already been cleared
                    while (clearedTokenIds[baseTokenId] != false) {
                        baseTokenId = (++baseTokenId) % 100;
                    }

                    delete tokenRecipient[baseTokenId];
                    clearedTokenIds[baseTokenId] = true;

                    emit MintUnscheduled(baseTokenId, i, cachedFounder);

                    // Update the base token id
                    baseTokenId = (baseTokenId + schedule) % 100;
                }
            }
        }

        // Clear values from storage before adding new founders
        settings.numFounders = 0;
        settings.totalOwnership = 0;
        emit FounderAllocationsCleared(newFounders);

        _addFounders(newFounders, reservedUntilTokenId);
    }
```

Duplicate of #42

**Comment by chaduke3730** [comment]
Escalate
This is an independent finding from #42. This is about wrong delete. #42 focuses on the case of  reservedUntilTokenId > 100 first funder loss 1% NFT, a different scenario.

**Comment by nevillehuang** [comment]
Will review all duplicates under #42, so please check deduplication comments [here](https://discord.com/channels/812037309376495636/1176899915411099719/1184507360765546556) in the mean time.

**Comment by nevillehuang** [comment]
See comment [here](https://github.com/sherlock-audit/2023-09-nounsbuilder-judging/issues/42#issuecomment-1857558554)

**Comment by Czar102** [comment]
I agree with the Lead Judge, @chaduke3730 could you look into it further and let me know if the justification provided in the comment linked above makes sense to you?

**Comment by Czar102** [comment]
Result:
High
Duplicate of #42

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [chaduke3730](https://github.com/sherlock-audit/2023-09-nounsbuilder-judging/issues/72/#issuecomment-1853977001): rejected
