### ISSUE TITLE
chaduke - updateFounders() and   setReservedUntilTokenId() might interfere with each other.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-nounsbuilder-judging#74]
chaduke

medium

# updateFounders() and   setReservedUntilTokenId() might interfere with each other.

## Summary
 setReservedUntilTokenId() will change the value of ``reservedUntilTokenId``. Meanwhile, updateFounders() will delete the old founders and add the new founders whose mapping is based on ``reservedUntilTokenId``.  As a result, if  setReservedUntilTokenId() is executed, then updateFounders()  cannot be correctly executed since the old  ``reservedUntilTokenId`` value is gone. Therefore, updateFounders() can be executed only  ``reservedUntilTokenId`` has never been changed. 

## Vulnerability Detail

setReservedUntilTokenId() will change the value of ``reservedUntilTokenId``.

[https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/token/Token.sol#L486-L503](https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/token/Token.sol#L486-L503)

``reservedUntilTokenId`` is used to establish the mapping in ``tokenRecipient[]``:

[https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/token/Token.sol#L120-L182](https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/token/Token.sol#L120-L182)

updateFounders()  needs to use ``reservedUntilTokenId`` (see my other report) to reverse engineer the right ``tokenRecipient[baseTokenId]`` to delete. 

if  ``setReservedUntilTokenId()`` is executed and we have a new ``reservedUntilTokenId``, then updateFounders()  will not be executed correctly. 

## Impact
updateFounders() and   setReservedUntilTokenId() might interfere with each other.  If setReservedUntilTokenId()  is executed first, then 
updateFounders() cannot be executed correctly and should not prevented. 

## Code Snippet
[https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/token/Token.sol#L120-L182](https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/token/Token.sol#L120-L182)

## Tool used
VScode. foundry

Manual Review

## Recommendation
Do not allow the execution of updateFounders() if setReservedUntilTokenId() has been executed to prevent wrong reverse enginneering in updateFounders() . 

Duplicate of #42

**Comment by chaduke3730** [comment]
Escalate
I think this is an independent finding, not the same as #42.

**Comment by sherlock-admin2** [comment]
> Escalate
> I think this is an independent finding, not the same as #42. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
Will review all duplicates under #42, so please check deduplication comments [here](https://discord.com/channels/812037309376495636/1176899915411099719/1184507360765546556) in the mean time.

**Comment by nevillehuang** [comment]
See comment [here](https://github.com/sherlock-audit/2023-09-nounsbuilder-judging/issues/42#issuecomment-1857558554)

**Comment by Czar102** [comment]
I agree with the Lead Judge, @chaduke3730 could you look into it further and let me know if the justification provided in the comment linked above makes sense to you?

If you think the fix provided by the sponsor is insufficient to solve this issue, please let me know.

**Comment by Czar102** [comment]
Result:
High
Duplicate of #42

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [chaduke3730](https://github.com/sherlock-audit/2023-09-nounsbuilder-judging/issues/74/#issuecomment-1853964440): rejected
